GET http://localhost:3000/login

###
### Registrarse
POST http://localhost:3000/register

Content-Type: application/json

{
  "email": "hola@gmail.com",
  "password": 1234
}


### 
## Iniciar Sesion
POST  http://localhost:3000/login

Content-Type: application/json

{
  "email": "brianheredia200309@gmail.com",
  "password": 1234
}

###

PATCH http://localhost:3000/login/3
Content-Type: application/json

{
  "email": "juanito@gmail.com",
  "password": 32
}